#ifndef __FUSIONDALE_VERSION_H__
#define __FUSIONDALE_VERSION_H__

#define FUSIONDALE_MAJOR_VERSION  ( 0 )
#define FUSIONDALE_MINOR_VERSION  ( 1 )
#define FUSIONDALE_MICRO_VERSION  ( 1 )
#define FUSIONDALE_BINARY_AGE     (0)
#define FUSIONDALE_INTERFACE_AGE  (0)


#endif
